# Generated by Django 6.0.6 on 2026-06-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termo',
            name='is_novo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='termo',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='termo',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=255, null=True),
        ),
    ]
