# Generated by Django 6.0.6 on 2026-06-09 14:27

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, help_text='Ex: Especialista em TI, Desenvolvedor', max_length=150)),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto de Perfil')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub URL')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.autor'),
        ),
    ]
