# Generated by Django 6.0.6 on 2026-06-09 11:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('icone', models.CharField(blank=True, help_text='Classe do ícone ou emoji', max_length=100)),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('descricao', models.TextField()),
                ('descricao_curta', models.CharField(blank=True, max_length=200)),
                ('url_projeto', models.URLField(blank=True, null=True, verbose_name='URL do Projeto')),
                ('url_repositorio', models.URLField(blank=True, null=True, verbose_name='Repositório (GitHub)')),
                ('imagem', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem do Projeto')),
                ('destaque', models.BooleanField(default=False, help_text='Exibir em destaque na homepage')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='projetos', to='portfolio.tecnologia')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['ordem', '-data_conclusao'],
            },
        ),
    ]
