# Generated by Django 6.0.6 on 2026-06-09 17:31

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, max_length=150, null=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição na galeria')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='portfolio.projeto')),
            ],
            options={
                'verbose_name': 'Imagem do Projeto',
                'verbose_name_plural': 'Imagens dos Projetos',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VideoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', cloudinary.models.CloudinaryField(blank=True, help_text='Upload de vídeo curto (Cloudinary)', max_length=255, null=True, verbose_name='Vídeo')),
                ('youtube_url', models.URLField(blank=True, help_text='Link do vídeo no YouTube', null=True, verbose_name='URL do YouTube')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição na galeria')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='portfolio.projeto')),
            ],
            options={
                'verbose_name': 'Vídeo do Projeto',
                'verbose_name_plural': 'Vídeos dos Projetos',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
